---
# Ansible Galaxy requirements for this project

# Roles
roles:
- src: gantsign.visual-studio-code

# Collections
collections:
- name: community.general
  version: ">=9.0.0"
- name: community.docker
  version: ">=3.4.5"